#define UNKNOWN      0
#define PLUS         1
#define MINUS        2
#define TIMES        3
#define DIVIDED      4
#define LPARENT      5
#define RPARENT      6
#define COMMA        7
#define PERIOD       8
#define BECOMES      9
#define ASSIG       10
#define EQUAL       11
#define LESS        12
#define GREATER     13
#define LESS_EQL    14
#define GREATER_EQL 15
#define IDENTIFIER  16
#define NUMBER      17
#define STRING      18
#define VARDEC      19
#define CONSTDEC    20
#define EOL         21
#define PRINT       22
#define LOAD        23
#define TYPEOF      24
#define EXIT        25
#define COLON       26
